services:
  postgres:
    image: postgres:17
    stop_grace_period: 0s
    container_name: postgres
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nuxt:
    container_name: nuxt
    stop_grace_period: 0s
    build:
      context: .
      dockerfile: nuxt.dockerfile
    env_file: .env
    restart: unless-stopped
    environment:
      PGPASSWORD: "${PGPASSWORD}"
      PGHOST: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
